// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyC4jDF_y7IOSmuanerrSsLjWkjoMs2pA',
    appId: '1:685582539479:web:21b90ce2d6943b2f102e92',
    messagingSenderId: '685582539479',
    projectId: 'footy-backend-d4eb8',
    authDomain: 'footy-backend-d4eb8.firebaseapp.com',
    storageBucket: 'footy-backend-d4eb8.firebasestorage.app',
    measurementId: 'G-VRB9FTLKNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLaryEIAy3gglScGb-7dB9MDugUGosg0',
    appId: '1:685582539479:android:827b1362ad117d2e102e92',
    messagingSenderId: '685582539479',
    projectId: 'footy-backend-d4eb8',
    storageBucket: 'footy-backend-d4eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_RJPjQMz1alK-F_mHrB4DGiovmBHwEIQ',
    appId: '1:685582539479:ios:d14898cef2619edc102e92',
    messagingSenderId: '685582539479',
    projectId: 'footy-backend-d4eb8',
    storageBucket: 'footy-backend-d4eb8.firebasestorage.app',
    iosBundleId: 'com.example.footyFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_RJPjQMz1alK-F_mHrB4DGiovmBHwEIQ',
    appId: '1:685582539479:ios:d14898cef2619edc102e92',
    messagingSenderId: '685582539479',
    projectId: 'footy-backend-d4eb8',
    storageBucket: 'footy-backend-d4eb8.firebasestorage.app',
    iosBundleId: 'com.example.footyFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyC4jDF_y7IOSmuanerrSsLjWkjoMs2pA',
    appId: '1:685582539479:web:552ffe9996354d5f102e92',
    messagingSenderId: '685582539479',
    projectId: 'footy-backend-d4eb8',
    authDomain: 'footy-backend-d4eb8.firebaseapp.com',
    storageBucket: 'footy-backend-d4eb8.firebasestorage.app',
    measurementId: 'G-1YNBM986DD',
  );

}